spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    generate-unique-name: false
    name: library
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  server:
    error:
      include-message: always
      include-binding-errors: always
      include-stacktrace: never
      include-exception: false
