create table if not exists Book (
    id varchar(256) primary key,
    book_name varchar(256) not null,
    released_year bigint not null,
    edition bigint not null,
    quantity bigint not null,
    placed_at date not null
);

create table if not exists Author (
    id bigint not null GENERATED BY DEFAULT AS IDENTITY,
    author_name varchar(256) not null,
    primary key(id)
);

create table if not exists Book_Author (
    book_id varchar(256),
    author_id varchar(256),
    primary key(book_id, author_id),
    foreign key (book_id) references Book(id),
    foreign key (author_id) references Author(id)
);